### ISSUE TITLE
TP to Nether crashes server - MNS might be the cause based on crash log

### ISSUE THREAD

**Issue by ZiLenTz** [FinnSetchell/MoogsNetherStructures#3]
Crash log indicated that it might be related to this
https://mclo.gs/W1gGpIv

```
java.lang.NoSuchFieldError: Class net.minecraft.class_3499$class_3501 does not have member field 'net.minecraft.class_2680 field_15596'
at com.finndog.mns.world.structures.pieces.PieceLimitedJigsawManager$Assembler.generatePiece(PieceLimitedJigsawManager.java:278)
at com.finndog.mns.world.structures.pieces.PieceLimitedJigsawManager.lambda$assembleJigsawStructure$2(PieceLimitedJigsawManager.java:175)
```

Behavior
- Teleporting from Overworld to Nether will either disconnecting the player or crashing the server entirely every time.
- After reconnecting, teleporting back from Nether to Overworld works fine.

Note: Teleported area in Nether was already pre-generated.

Version
- Minecraft 1.20.1
- Fabric Loader 0.15.6
- Moog's Nether Structures 1.0.0

**Comment by ZiLenTz** [comment]
After checking your Discord, seems like MNS 1.0.0 isn't supposed to work with MC 1.20.1.
Downgrading it to MNS 1.0 works.
